%TEST_ACTUATOR_DYNAMICS Validate the first-cut control-surface actuator model.

scriptPath = mfilename('fullpath');
featureTestDir = fileparts(scriptPath);
testsDir = fileparts(featureTestDir);
projectRoot = fileparts(testsDir);

addpath(fullfile(projectRoot, 'data'));
addpath(fullfile(projectRoot, 'plant'));

actuator = b777_actuator_model();

assert(actuator.id == "B777_ACTUATOR_MODEL_V0", ...
    'Unexpected actuator model identifier.');
assert(numel(actuator.surface_names) == 3, ...
    'Actuator model should expose elevator, aileron and rudder.');
assertRange(actuator.elevator.position_max_deg, 20.0, 30.0, ...
    'elevator positive position limit');
assertRange(actuator.aileron.position_max_deg, 15.0, 25.0, ...
    'aileron positive position limit');
assertRange(actuator.rudder.position_max_deg, 25.0, 35.0, ...
    'rudder positive position limit');
assertRange(actuator.elevator.tau_s, 0.05, 0.50, ...
    'elevator actuator time constant');

state = struct();
state.delta_e_rad = 0.0;
state.delta_a_rad = 0.0;
state.delta_r_rad = 0.0;

neutral = b777_actuator_dynamics(state, struct());
assertVectorClose(neutral.actual_rad, [0.0; 0.0; 0.0], 1e-12, ...
    'neutral actual surfaces');
assertVectorClose(neutral.derivative_radps, [0.0; 0.0; 0.0], 1e-12, ...
    'neutral actuator derivatives');

command = struct();
command.delta_e_cmd_rad = deg2rad_local(40.0);
command.delta_a_cmd_rad = deg2rad_local(-40.0);
command.delta_r_cmd_rad = deg2rad_local(50.0);
saturated = b777_actuator_dynamics(state, command);

assertClose(saturated.commanded_limited_rad(1), ...
    actuator.elevator.position_max_rad, 1e-12, ...
    'elevator command saturation');
assertClose(saturated.commanded_limited_rad(2), ...
    actuator.aileron.position_min_rad, 1e-12, ...
    'aileron command saturation');
assertClose(saturated.commanded_limited_rad(3), ...
    actuator.rudder.position_max_rad, 1e-12, ...
    'rudder command saturation');
assert(saturated.limits.command_saturated(1) && ...
        saturated.limits.command_saturated(2) && ...
        saturated.limits.command_saturated(3), ...
    'Out-of-range commands should be marked as saturated.');
assertClose(saturated.derivative_radps(1), ...
    actuator.elevator.rate_max_radps, 1e-12, ...
    'elevator positive rate limit');
assertClose(saturated.derivative_radps(2), ...
    actuator.aileron.rate_min_radps, 1e-12, ...
    'aileron negative rate limit');
assertClose(saturated.derivative_radps(3), ...
    actuator.rudder.rate_max_radps, 1e-12, ...
    'rudder positive rate limit');

stateAtLimit = state;
stateAtLimit.delta_e_rad = actuator.elevator.position_max_rad;
commandPastLimit = struct();
commandPastLimit.delta_e_cmd_rad = actuator.elevator.position_max_rad ...
    + deg2rad_local(5.0);
blocked = b777_actuator_dynamics(stateAtLimit, commandPastLimit);
assertClose(blocked.delta_e_dot_radps, 0.0, 1e-12, ...
    'elevator should not drive farther into a position limit');

commandBack = struct();
commandBack.delta_e_cmd_rad = actuator.elevator.position_min_rad;
recovering = b777_actuator_dynamics(stateAtLimit, commandBack);
assert(recovering.delta_e_dot_radps < 0.0, ...
    'elevator should move away from the positive position limit.');

stateOutOfRange = state;
stateOutOfRange.delta_a_rad = deg2rad_local(80.0);
limitedState = b777_actuator_dynamics(stateOutOfRange, struct());
assertClose(limitedState.delta_a_rad, actuator.aileron.position_max_rad, ...
    1e-12, 'actual aileron position saturation');
assert(limitedState.limits.position_saturated(2), ...
    'Out-of-range actual aileron state should be marked as saturated.');

vectorCommand = [deg2rad_local(1.0); deg2rad_local(-1.0); ...
    deg2rad_local(2.0)];
vectorAct = b777_actuator_dynamics(state, vectorCommand);
assert(vectorAct.delta_e_dot_radps > 0.0, ...
    'Positive elevator vector command should give positive elevator rate.');
assert(vectorAct.delta_a_dot_radps < 0.0, ...
    'Negative aileron vector command should give negative aileron rate.');
assert(vectorAct.delta_r_dot_radps > 0.0, ...
    'Positive rudder vector command should give positive rudder rate.');
assertClose(vectorAct.control.delta_e_rad, state.delta_e_rad, 1e-12, ...
    'aero control elevator output should use current actual deflection');
assertClose(vectorAct.control.delta_a_rad, state.delta_a_rad, 1e-12, ...
    'aero control aileron output should use current actual deflection');
assertClose(vectorAct.control.delta_r_rad, state.delta_r_rad, 1e-12, ...
    'aero control rudder output should use current actual deflection');

fprintf('Feature test passed: actuator dynamics are defined consistently.\n');

function assertRange(value, lowerBound, upperBound, label)
    assert(value >= lowerBound && value <= upperBound, ...
        '%s is outside expected range: %.8g', label, value);
end

function assertClose(value, expected, tolerance, label)
    assert(abs(value - expected) <= tolerance, ...
        '%s mismatch: got %.16g, expected %.16g', label, value, expected);
end

function assertVectorClose(value, expected, tolerance, label)
    assert(all(abs(value(:) - expected(:)) <= tolerance), ...
        '%s mismatch.', label);
end

function value_rad = deg2rad_local(value_deg)
    value_rad = value_deg * pi / 180.0;
end
