%TEST_AERODYNAMIC_DATABASE Validate the staged aerodynamic database.

scriptPath = mfilename('fullpath');
featureTestDir = fileparts(scriptPath);
testsDir = fileparts(featureTestDir);
projectRoot = fileparts(testsDir);

addpath(fullfile(projectRoot, 'data'));
addpath(fullfile(projectRoot, 'data', 'aerodynamics'));
addpath(fullfile(projectRoot, 'plant'));

aeroDataRoot = fullfile(projectRoot, 'data', 'aerodynamics');
aeroRawRoot = fullfile(aeroDataRoot, 'raw');
aeroValidationRoot = fullfile(aeroDataRoot, 'validation');

geom = b777_geometry();
aero = b777_aero_database();

assertClose(aero.reference.S_m2, geom.wing.area_m2, 1e-12, ...
    'aero reference area');
assertClose(aero.reference.b_m, geom.wing.span_m, 1e-12, ...
    'aero reference span');
assertClose(aero.reference.c_m, geom.wing.mean_aerodynamic_chord_m, 1e-12, ...
    'aero reference chord');

assert(hasSource(aero.sources, "NASA_CRM_CLEAN"), ...
    'NASA CRM clean source must be registered.');
assert(hasSource(aero.sources, "NASA_CRM_NTF197_TWICS_CLEAN_GRID"), ...
    'NASA CRM NTF197 clean grid source must be registered.');
assert(hasSource(aero.sources, "NASA_CRM_CFD_M085_ORIG_WBT0"), ...
    'NASA CRM M=0.85 CFD cross-check source must be registered.');
assert(hasSource(aero.sources, "USAF_DATCOM"), ...
    'DATCOM source must be registered.');
assert(hasSource(aero.sources, "DATCOM_DERIVATIVE_SEED_B777_LIKE_V0"), ...
    'DATCOM-ready derivative seed source must be registered.');
assert(hasSource(aero.sources, ...
        "DIGITAL_DATCOM_B777_LIKE_MACH_GRID_CANDIDATE_V0"), ...
    'Digital DATCOM Mach-grid candidate source must be registered.');
assert(hasSource(aero.sources, ...
        "DIGITAL_DATCOM_B777_LIKE_CONTROL_GRID_CANDIDATE_V0"), ...
    'Digital DATCOM control-grid candidate source must be registered.');
assert(hasSource(aero.sources, ...
        "DIGITAL_DATCOM_B777_LIKE_DERIVED_GAP_FILL_CANDIDATE_V0"), ...
    'Digital DATCOM derived gap-fill candidate source must be registered.');
assert(hasSource(aero.sources, ...
        "DATCOM_CANDIDATE_LONGITUDINAL_TRIM_VALIDATION_V0"), ...
    'DATCOM trim validation source must be registered.');
assert(hasSource(aero.sources, ...
        "DATCOM_CANDIDATE_LONGITUDINAL_MODAL_VALIDATION_V0"), ...
    'DATCOM longitudinal modal validation source must be registered.');
assert(hasSource(aero.sources, "NASA_CRM_HL"), ...
    'CRM-HL source must be registered.');
assert(hasSource(aero.sources, "CRMHL_DATCOM_HIGH_LIFT_SEED_B777_LIKE_V0"), ...
    'CRM-HL/DATCOM-ready high-lift seed source must be registered.');
assert(hasSource(aero.sources, "OPENFOAM_CHECKS"), ...
    'OpenFOAM validation source must be registered.');

assert(hasDerivative(aero.derivatives, "CL_alpha"), ...
    'CL_alpha derivative must be inventoried.');
assert(hasDerivative(aero.derivatives, "Cm_q"), ...
    'Cm_q derivative must be inventoried.');
assert(hasDerivative(aero.derivatives, "high_lift_increments"), ...
    'High-lift increments must be inventoried.');

cleanTable = aero.tables.clean_cruise;
assert(cleanTable.id == "NASA_CRM_NTF197_TWICS_CLEAN_GRID", ...
    'Unexpected clean cruise table identifier.');
assert(cleanTable.grid.status == "multi-Mach-alpha-grid", ...
    'Clean table must expose the multi-Mach grid interface.');
assert(numel(cleanTable.grid.Mach) == 7, ...
    'Clean grid must contain the selected NTF197 Mach stations.');
assert(numel(cleanTable.grid.alpha_rad) == 12, ...
    'Clean grid must contain the curated alpha stations.');
assert(isequal(size(cleanTable.CL), ...
        [numel(cleanTable.alpha_rad), numel(cleanTable.Mach)]), ...
    'Clean table CL matrix must be alpha-by-Mach.');
assert(isequal(size(cleanTable.CD), ...
        [numel(cleanTable.alpha_rad), numel(cleanTable.Mach)]), ...
    'Clean table CD matrix must be alpha-by-Mach.');
assert(isequal(size(cleanTable.Cm), ...
        [numel(cleanTable.alpha_rad), numel(cleanTable.Mach)]), ...
    'Clean table Cm matrix must be alpha-by-Mach.');
assert(cleanTable.source.run_ids(1) == "R87", ...
    'First selected clean-grid run should be R87.');
assert(cleanTable.source.run_ids(5) == "R92", ...
    'M=0.85 clean-grid run should be R92.');

gridFile = fullfile(aeroRawRoot, 'nasa_crm', ...
    'NTF197_TWICS_clean_grid.csv');
rawGrid = b777_aero_read_crm_clean_grid_csv(gridFile);
r92MachIndex = find(abs(rawGrid.Mach - 0.85006) < 1e-10, 1);
alpha2Index = find(abs(rawGrid.alpha_deg - 2.0) < 1e-10, 1);
assert(~isempty(r92MachIndex), 'R92 Mach station must be present.');
assert(~isempty(alpha2Index), 'Alpha=2 deg station must be present.');
assertClose(rawGrid.CL(alpha2Index, r92MachIndex), 0.35404762, 1e-10, ...
    'raw NTF197 grid CL at R92 alpha=2 deg');
assertClose(rawGrid.CD(alpha2Index, r92MachIndex), 0.02010267, 1e-10, ...
    'raw NTF197 grid CD at R92 alpha=2 deg');
assertClose(rawGrid.Cm(alpha2Index, r92MachIndex), 0.08044518, 1e-10, ...
    'raw NTF197 grid Cm at R92 alpha=2 deg');

cfdRawFile = fullfile(aeroRawRoot, 'nasa_crm', ...
    'NASA_wbt0_M85_CFD_orig.csv');
rawTable = b777_aero_read_crm_force_moment_csv(cfdRawFile);
assertClose(rawTable.CL(4), 0.46611, 1e-12, ...
    'raw CRM CFD cross-check CL at alpha=2 deg');
assertClose(rawTable.CD(4), 0.02585, 1e-12, ...
    'raw CRM CFD cross-check CD at alpha=2 deg');
assertClose(rawTable.Cm(4), -0.03992, 1e-12, ...
    'raw CRM CFD cross-check Cm at alpha=2 deg');

derivativeSeed = aero.tables.derivative_seed;
assert(derivativeSeed.id == "DATCOM_DERIVATIVE_SEED_B777_LIKE_V0", ...
    'Unexpected derivative seed identifier.');
assert(derivativeSeed.primary_source_id == "USAF_DATCOM", ...
    'Derivative seed should point to DATCOM as the replacement source.');
assert(derivativeSeed.status == "datcom-ready-seed-active", ...
    'Derivative seed should be active in DATCOM-ready format.');
assertClose(derivativeSeed.static.CY_beta, -0.85, 1e-12, ...
    'DATCOM-ready derivative table CY_beta');
assert(derivativeSeed.control.Cm_delta_e < 0.0, ...
    'Positive elevator should produce negative pitching moment.');
assert(derivativeSeed.control.Cl_delta_a > 0.0, ...
    'Positive effective aileron should produce positive rolling moment.');
assert(derivativeSeed.control.Cn_delta_r > 0.0, ...
    'Positive rudder should produce positive yawing moment.');
assert(derivativeSeed.dynamic.Cm_q < 0.0, ...
    'Pitch damping derivative should be negative.');

datcomInputFile = fullfile(aeroRawRoot, 'datcom', ...
    'b777_like_digital_datcom_static_damping.inp');
datcomCandidateFile = fullfile(aeroRawRoot, 'datcom', ...
    'b777_like_derivative_datcom_candidate_m060.csv');
datcomMachGridIndexFile = fullfile(aeroRawRoot, 'datcom', ...
    'mach_grid', 'b777_like_datcom_mach_grid_run_index.csv');
datcomMachGridCandidateFile = fullfile(aeroRawRoot, 'datcom', ...
    'mach_grid', 'b777_like_derivative_datcom_candidate_mach_grid.csv');
datcomMachGridReportFile = fullfile(aeroRawRoot, 'datcom', ...
    'mach_grid', 'b777_like_derivative_datcom_candidate_mach_grid_report.txt');
datcomPromotionGateFile = fullfile(aeroRawRoot, 'datcom', ...
    'mach_grid', 'b777_like_derivative_datcom_promotion_gates.csv');
datcomPromotionReportFile = fullfile(aeroRawRoot, 'datcom', ...
    'mach_grid', 'b777_like_derivative_datcom_promotion_gates.txt');
datcomControlGridIndexFile = fullfile(aeroRawRoot, 'datcom', ...
    'control_grid', 'b777_like_datcom_control_grid_run_index.csv');
datcomControlGridCandidateFile = fullfile(aeroRawRoot, ...
    'datcom', 'control_grid', ...
    'b777_like_control_derivative_datcom_candidate_mach_grid.csv');
datcomControlGridReportFile = fullfile(aeroRawRoot, ...
    'datcom', 'control_grid', ...
    'b777_like_control_derivative_datcom_candidate_mach_grid_report.txt');
datcomGapFillCandidateFile = fullfile(aeroRawRoot, ...
    'datcom', 'derived_gap_fill', ...
    'b777_like_derivative_gap_fill_candidate_mach_grid.csv');
datcomGapFillReportFile = fullfile(aeroRawRoot, ...
    'datcom', 'derived_gap_fill', ...
    'b777_like_derivative_gap_fill_candidate_mach_grid_report.txt');
trimValidationCaseFile = fullfile(aeroValidationRoot, ...
    'trim_validation_cases.csv');
trimValidationReportFile = fullfile(projectRoot, 'docs', ...
    'trim_validation_report.md');
modalValidationCaseFile = fullfile(aeroValidationRoot, ...
    'longitudinal_modal_validation_cases.csv');
modalValidationReportFile = fullfile(projectRoot, 'docs', ...
    'longitudinal_modal_validation_report.md');
assert(isfile(datcomInputFile), ...
    'Digital DATCOM input deck must be present.');
assert(isfile(datcomCandidateFile), ...
    'Digital DATCOM candidate derivative CSV must be present.');
assert(isfile(datcomMachGridIndexFile), ...
    'Digital DATCOM Mach-grid run index must be present.');
assert(isfile(datcomMachGridCandidateFile), ...
    'Digital DATCOM Mach-grid candidate table must be present.');
assert(isfile(datcomMachGridReportFile), ...
    'Digital DATCOM Mach-grid candidate report must be present.');
assert(isfile(datcomPromotionGateFile), ...
    'Digital DATCOM promotion gate CSV must be present.');
assert(isfile(datcomPromotionReportFile), ...
    'Digital DATCOM promotion gate report must be present.');
assert(isfile(datcomControlGridIndexFile), ...
    'Digital DATCOM control-grid run index must be present.');
assert(isfile(datcomControlGridCandidateFile), ...
    'Digital DATCOM control-grid candidate table must be present.');
assert(isfile(datcomControlGridReportFile), ...
    'Digital DATCOM control-grid report must be present.');
assert(isfile(datcomGapFillCandidateFile), ...
    'Digital DATCOM derived gap-fill candidate table must be present.');
assert(isfile(datcomGapFillReportFile), ...
    'Digital DATCOM derived gap-fill report must be present.');
assert(isfile(trimValidationCaseFile), ...
    'DATCOM trim validation case table must be present.');
assert(isfile(trimValidationReportFile), ...
    'DATCOM trim validation report must be present.');
assert(isfile(modalValidationCaseFile), ...
    'DATCOM longitudinal modal validation case table must be present.');
assert(isfile(modalValidationReportFile), ...
    'DATCOM longitudinal modal validation report must be present.');
datcomCandidate = readPartialDerivativeCsv(datcomCandidateFile);
assert(datcomCandidate.source_id == ...
        "DIGITAL_DATCOM_B777_LIKE_M060_CANDIDATE_V0", ...
    'Unexpected DATCOM candidate source identifier.');
assert(datcomCandidate.status == "candidate-pending-review", ...
    'DATCOM candidate values must not be marked as active.');
assertClose(datcomCandidate.static.CY_beta, -0.37906888, 1e-8, ...
    'DATCOM candidate CY_beta');
assert(datcomCandidate.static.CY_beta < 0.0, ...
    'DATCOM candidate CY_beta should be negative.');
assert(datcomCandidate.static.Cl_beta < 0.0, ...
    'DATCOM candidate Cl_beta should be negative.');
assert(datcomCandidate.static.Cn_beta > 0.0, ...
    'DATCOM candidate Cn_beta should be positive.');
assert(datcomCandidate.dynamic.Cl_p < 0.0, ...
    'DATCOM candidate Cl_p should be negative.');
assert(datcomCandidate.dynamic.Cm_q < 0.0, ...
    'DATCOM candidate Cm_q should be negative.');
assert(datcomCandidate.dynamic.Cn_r < 0.0, ...
    'DATCOM candidate Cn_r should be negative.');

datcomMachGridIndex = string(fileread(datcomMachGridIndexFile));
assert(contains(datcomMachGridIndex, "case_id,mach,input_file"), ...
    'Digital DATCOM Mach-grid index must have the expected header.');
assert(contains(datcomMachGridIndex, ...
        "datcom_exit_status,error_count,warning_count"), ...
    'Digital DATCOM Mach-grid index must expose run-quality columns.');
datcomMachCases = ["m030", "m050", "m060", "m070", "m080"];
for k = 1:numel(datcomMachCases)
    caseId = char(datcomMachCases(k));
    candidateFile = fullfile(aeroRawRoot, 'datcom', ...
        'mach_grid', ['b777_like_derivative_datcom_candidate_' caseId '.csv']);
    candidateIndexPath = ['data/aerodynamics/raw/datcom/mach_grid/' ...
        'b777_like_derivative_datcom_candidate_' caseId '.csv'];
    assert(contains(datcomMachGridIndex, caseId), ...
        'Digital DATCOM Mach-grid index must contain case %s.', caseId);
    assert(contains(datcomMachGridIndex, candidateIndexPath), ...
        'Digital DATCOM Mach-grid index must point to candidate %s.', ...
        caseId);
    assert(isfile(candidateFile), ...
        'Digital DATCOM Mach-grid candidate file missing for %s.', caseId);

    candidate = readPartialDerivativeCsv(candidateFile);
    expectedSourceId = "DIGITAL_DATCOM_B777_LIKE_" + ...
        upper(string(caseId)) + "_CANDIDATE_V0";
    assert(candidate.source_id == expectedSourceId, ...
        'Unexpected Digital DATCOM Mach-grid source id for %s.', caseId);
    assert(candidate.status == "candidate-pending-review", ...
        'Digital DATCOM Mach-grid values must remain candidates for %s.', ...
        caseId);
    assert(candidate.static.CY_beta < 0.0, ...
        'Digital DATCOM Mach-grid CY_beta should be negative for %s.', ...
        caseId);
    assert(candidate.static.Cl_beta < 0.0, ...
        'Digital DATCOM Mach-grid Cl_beta should be negative for %s.', ...
        caseId);
    assert(candidate.static.Cn_beta > 0.0, ...
        'Digital DATCOM Mach-grid Cn_beta should be positive for %s.', ...
        caseId);
    assert(candidate.dynamic.Cl_p < 0.0, ...
        'Digital DATCOM Mach-grid Cl_p should be negative for %s.', ...
        caseId);
    assert(candidate.dynamic.Cm_q < 0.0, ...
        'Digital DATCOM Mach-grid Cm_q should be negative for %s.', ...
        caseId);
    assert(candidate.dynamic.Cn_r < 0.0, ...
        'Digital DATCOM Mach-grid Cn_r should be negative for %s.', ...
        caseId);
end
assert(count(datcomMachGridIndex, ",0,0,") == numel(datcomMachCases), ...
    'Digital DATCOM Mach-grid index should record successful zero-error runs.');
datcomMachGrid = b777_aero_read_mach_derivative_csv( ...
    datcomMachGridCandidateFile);
datcomMachGridReport = string(fileread(datcomMachGridReportFile));
assert(datcomMachGrid.source_id == ...
        "DIGITAL_DATCOM_B777_LIKE_MACH_GRID_CANDIDATE_V0", ...
    'Unexpected Digital DATCOM consolidated Mach-grid source id.');
assert(isequal(datcomMachGrid.Mach(:), [0.30; 0.50; 0.60; 0.70; 0.80]), ...
    'Digital DATCOM consolidated Mach grid mismatch.');
assert(isequal(size(datcomMachGrid.grid.value), [5, 10]), ...
    'Digital DATCOM consolidated Mach grid should be 5-by-10.');
assert(contains(datcomMachGridReport, "mach_count=5"), ...
    'Digital DATCOM consolidated report must record five Mach points.');
assert(contains(datcomMachGridReport, ...
        "linear in Mach inside committed grid"), ...
    'Digital DATCOM consolidated report must record interpolation policy.');
assertClose(datcomMachGrid.static.Cn_beta(5), 0.04693097, 1e-8, ...
    'Digital DATCOM consolidated Cn_beta at Mach 0.80');
assert(all(diff(datcomMachGrid.static.Cn_beta) < 0.0), ...
    'Digital DATCOM Cn_beta trend should decrease over the current Mach grid.');
assert(all(diff(datcomMachGrid.dynamic.Cm_q) > 0.0), ...
    'Digital DATCOM Cm_q should become less negative over the current Mach grid.');
datcomPromotionReport = string(fileread(datcomPromotionReportFile));
datcomControlGridReport = string(fileread(datcomControlGridReportFile));
datcomControlGridIndex = string(fileread(datcomControlGridIndexFile));
datcomGapFillReport = string(fileread(datcomGapFillReportFile));
trimValidationReport = string(fileread(trimValidationReportFile));
modalValidationReport = string(fileread(modalValidationReportFile));
assert(contains(datcomControlGridIndex, "elevator_m060") && ...
        contains(datcomControlGridIndex, "aileron_m060"), ...
    'Digital DATCOM control-grid index should include elevator and aileron cases.');
assert(contains(datcomControlGridReport, ...
        "source_id=DIGITAL_DATCOM_B777_LIKE_CONTROL_GRID_CANDIDATE_V0"), ...
    'Digital DATCOM control-grid report must record the control source id.');
assert(contains(datcomControlGridReport, "CL_delta_e: count=5"), ...
    'Digital DATCOM control-grid report must include elevator lift effectiveness.');
assert(contains(datcomControlGridReport, "Cl_delta_a: count=5"), ...
    'Digital DATCOM control-grid report must include aileron roll effectiveness.');
assert(contains(datcomControlGridReport, ...
        "missing_active_control_coefficients=CD_delta_a"), ...
    'Digital DATCOM control-grid report must record remaining control gaps.');
assert(contains(datcomGapFillReport, ...
        "source_id=DIGITAL_DATCOM_B777_LIKE_DERIVED_GAP_FILL_CANDIDATE_V0"), ...
    'Digital DATCOM derived gap-fill report must record the gap-fill source id.');
assert(contains(datcomGapFillReport, "CD_beta: count=5"), ...
    'Digital DATCOM derived gap-fill report must include sideslip drag coverage.');
assert(contains(datcomGapFillReport, "CY_r: count=5"), ...
    'Digital DATCOM derived gap-fill report must include yaw-rate side-force coverage.');
assert(contains(datcomGapFillReport, "Cn_delta_r: count=5"), ...
    'Digital DATCOM derived gap-fill report must include rudder yaw coverage.');
assert(contains(trimValidationReport, ...
        "source_id=DATCOM_CANDIDATE_LONGITUDINAL_TRIM_VALIDATION_V0"), ...
    'DATCOM trim validation report must record the validation source id.');
assert(contains(trimValidationReport, "pass_count=3"), ...
    'DATCOM trim validation report should pass three clean-cruise cases.');
assert(contains(trimValidationReport, ...
        "DATCOM_PROMOTION_TRIM_VALIDATED=true"), ...
    'DATCOM trim validation report should recommend trim promotion.');
assert(contains(modalValidationReport, ...
        "source_id=DATCOM_CANDIDATE_LONGITUDINAL_MODAL_VALIDATION_V0"), ...
    'DATCOM longitudinal modal validation report must record the validation source id.');
assert(contains(modalValidationReport, "case_count=3"), ...
    'DATCOM longitudinal modal validation report should validate three cases.');
assert(contains(modalValidationReport, "mode_pair_count=6"), ...
    'DATCOM longitudinal modal validation report should validate six mode pairs.');
assert(contains(modalValidationReport, "pass_count=6"), ...
    'DATCOM longitudinal modal validation report should pass six clean-cruise mode pairs.');
assert(contains(modalValidationReport, ...
        "DATCOM_PROMOTION_MODAL_VALIDATED=true"), ...
    'DATCOM longitudinal modal validation report should recommend modal promotion.');
assert(contains(datcomPromotionReport, "promotion_allowed=false"), ...
    'Digital DATCOM promotion should remain blocked while warning review is open.');
assert(contains(datcomPromotionReport, "blocker_count=0"), ...
    'Digital DATCOM promotion report should have no remaining blockers.');
assert(contains(datcomPromotionReport, "review_count=1"), ...
    'Digital DATCOM promotion report should retain the warning-review item.');
assert(contains(datcomPromotionReport, "active_table_coverage: status=pass"), ...
    'Digital DATCOM promotion report should pass active-table coverage with gap-fill candidates.');
assert(contains(datcomPromotionReport, "control_derivatives: status=pass"), ...
    'Digital DATCOM promotion report should pass control derivatives with gap-fill candidates.');
assert(contains(datcomPromotionReport, "control.CL_delta_e") && ...
        contains(datcomPromotionReport, "control.Cl_delta_a"), ...
    'Digital DATCOM promotion report should see the control-grid candidates.');
assert(contains(datcomPromotionReport, "control.CD_delta_r") && ...
        contains(datcomPromotionReport, "static.CD_beta") && ...
        contains(datcomPromotionReport, "dynamic.CY_r"), ...
    'Digital DATCOM promotion report should see the derived gap-fill candidates.');
assert(contains(datcomPromotionReport, "trim_validation: status=pass"), ...
    'Digital DATCOM promotion report should pass trim validation.');
assert(contains(datcomPromotionReport, "modal_validation: status=pass"), ...
    'Digital DATCOM promotion report should pass modal validation.');

highLift = aero.tables.high_lift;
assert(highLift.id == "CRMHL_DATCOM_HIGH_LIFT_SEED_B777_LIKE_V0", ...
    'Unexpected high-lift seed identifier.');
assert(highLift.status == "crmhl-datcom-ready-seed-active", ...
    'High-lift seed should be active in CRM-HL/DATCOM-ready format.');
assert(numel(highLift.configs) == 3, ...
    'High-lift table must expose clean, approach and landing configs.');
assert(highLift.configs(1).name == "clean", ...
    'First high-lift config should be clean.');
assert(highLift.configs(2).name == "approach", ...
    'Second high-lift config should be approach.');
assert(highLift.configs(3).name == "landing", ...
    'Third high-lift config should be landing.');
assert(highLift.configs(2).increments.CL0 > ...
    highLift.configs(1).increments.CL0, ...
    'Approach high-lift seed must increase CL0 relative to clean.');
assert(highLift.configs(3).increments.CD0 > ...
    highLift.configs(2).increments.CD0, ...
    'Landing high-lift seed must increase CD0 relative to approach.');
assert(highLift.configs(2).slat_deployed, ...
    'Approach high-lift seed should deploy slats.');
assert(highLift.configs(3).gear_down, ...
    'Landing high-lift seed should include landing gear.');
assert(highLift.configs(3).CLmax_estimate > ...
    highLift.configs(2).CLmax_estimate, ...
    'Landing CLmax estimate must exceed approach CLmax estimate.');

highLiftFile = fullfile(aeroRawRoot, 'high_lift', ...
    'b777_like_high_lift_seed.csv');
rawHighLift = b777_aero_read_high_lift_csv(highLiftFile);
assert(rawHighLift.source_id == "CRMHL_DATCOM_HIGH_LIFT_SEED_B777_LIKE_V0", ...
    'Raw high-lift table source id mismatch.');
assertClose(rawHighLift.configs(2).increments.CL0, 0.65, 1e-12, ...
    'raw high-lift approach delta CL0');
assertClose(rawHighLift.configs(3).CLmax_estimate, 2.55, 1e-12, ...
    'raw high-lift landing CLmax estimate');

state = struct();
state.V_mps = 240.0;
state.Mach = cleanTable.grid.Mach(r92MachIndex);
state.h_m = 10668.0;
state.alpha_rad = deg2rad_local(2.0);
state.beta_rad = 0.0;
state.p_radps = 0.0;
state.q_radps = 0.0;
state.r_radps = 0.0;

control = struct();
control.delta_e_rad = 0.0;
control.delta_a_rad = 0.0;
control.delta_r_rad = 0.0;

clean = aero.coeff(state, control, "clean");
approach = aero.coeff(state, control, "approach");
landing = aero.coeff(state, control, "landing");

assertRange(clean.CL, 0.20, 0.80, 'clean seed CL');
assertRange(clean.CD, 0.01, 0.08, 'clean seed CD');
assertRange(clean.Cm, -0.20, 0.20, 'clean seed Cm');
assertClose(clean.CL, 0.35404762, 1e-10, ...
    'clean CRM NTF197 grid CL at R92 alpha=2 deg');
assertClose(clean.CD, 0.02010267, 1e-10, ...
    'clean CRM NTF197 grid CD at R92 alpha=2 deg');
assertClose(clean.Cm, 0.08044518, 1e-10, ...
    'clean CRM NTF197 grid Cm at R92 alpha=2 deg');
assert(clean.current_source_id == "NASA_CRM_NTF197_TWICS_CLEAN_GRID", ...
    'Clean sample should use the NASA CRM NTF197 grid.');
assert(clean.residual_derivative_source_id == ...
        "DATCOM_DERIVATIVE_SEED_B777_LIKE_V0", ...
    'Clean sample should use the DATCOM-ready derivative residual table.');

assert(approach.CL > clean.CL, ...
    'Approach configuration must increase lift in the seed model.');
assert(landing.CL > approach.CL, ...
    'Landing configuration must increase lift relative to approach.');
assert(approach.CD > clean.CD, ...
    'Approach configuration must increase drag in the seed model.');
assert(landing.CD > approach.CD, ...
    'Landing configuration must increase drag relative to approach.');
assert(clean.validity_status == "inside-seed-validity", ...
    'Sample clean case should be inside seed-model validity.');
assert(approach.config_increment_source_id == ...
        "CRMHL_DATCOM_HIGH_LIFT_SEED_B777_LIKE_V0", ...
    'Approach sample should use the CRM-HL/DATCOM-ready high-lift table.');
assert(landing.config_increment_source_id == ...
        "CRMHL_DATCOM_HIGH_LIFT_SEED_B777_LIKE_V0", ...
    'Landing sample should use the CRM-HL/DATCOM-ready high-lift table.');
assertClose(clean.CLmax_estimate, 1.45, 1e-12, ...
    'clean CLmax estimate');
assertClose(approach.CLmax_estimate, 2.15, 1e-12, ...
    'approach CLmax estimate');
assertClose(landing.CLmax_estimate, 2.55, 1e-12, ...
    'landing CLmax estimate');
assert(approach.CL_margin_to_estimate > clean.CL_margin_to_estimate, ...
    'Approach CLmax margin should increase relative to clean.');
assert(landing.gear_down, ...
    'Landing coefficient metadata should include gear-down state.');

fallbackState = state;
fallbackState.Mach = 0.68;
fallback = aero.coeff(fallbackState, control, "clean");
assert(fallback.current_source_id == "INITIAL_ANALYTIC_SEED", ...
    'Out-of-table clean case should fall back to analytical seed.');
assert(fallback.table_status == "fallback-analytic-seed", ...
    'Fallback table status should identify the analytical seed fallback.');

betaFallbackState = state;
betaFallbackState.beta_rad = deg2rad_local(2.0);
betaFallback = aero.coeff(betaFallbackState, control, "clean");
assert(betaFallback.current_source_id == "INITIAL_ANALYTIC_SEED", ...
    'Out-of-table beta case should fall back to analytical seed.');
assert(betaFallback.residual_derivative_source_id == "INITIAL_ANALYTIC_SEED", ...
    'Out-of-table beta case should use analytical residual derivatives.');

sideState = state;
sideState.beta_rad = deg2rad_local(0.5);
sideCoeff = aero.coeff(sideState, control, "clean");
assert(sideCoeff.residual_derivative_source_id == ...
        "DATCOM_DERIVATIVE_SEED_B777_LIKE_V0", ...
    'In-grid sideslip case should use DATCOM-ready derivatives.');
assertClose(sideCoeff.CY, ...
    derivativeSeed.static.CY_beta * sideState.beta_rad, 1e-12, ...
    'DATCOM-ready CY_beta residual');
assertClose(sideCoeff.Cl, ...
    derivativeSeed.static.Cl_beta * sideState.beta_rad, 1e-12, ...
    'DATCOM-ready Cl_beta residual');
assertClose(sideCoeff.Cn, ...
    derivativeSeed.static.Cn_beta * sideState.beta_rad, 1e-12, ...
    'DATCOM-ready Cn_beta residual');
assertClose(sideCoeff.CD - clean.CD, ...
    derivativeSeed.static.CD_beta * sideState.beta_rad^2, 1e-12, ...
    'DATCOM-ready CD_beta residual');

cleanLoads = b777_aero_forces_moments(state, control, "clean");
approachLoads = b777_aero_forces_moments(state, control, "approach");

expectedAtm = b777_atmosphere_isa(state.h_m);
expectedQbar = 0.5 * expectedAtm.rho_kgm3 * state.V_mps^2;
assertClose(cleanLoads.dynamic_pressure_Pa, expectedQbar, 1e-8, ...
    'aerodynamic dynamic pressure');
assert(cleanLoads.force_wind_N(1) < 0.0, ...
    'Wind-axis drag force must oppose the air-relative velocity.');
assert(cleanLoads.force_body_N(3) < 0.0, ...
    'Positive CL must produce upward body-axis force.');
assert(approachLoads.force_body_N(3) < cleanLoads.force_body_N(3), ...
    'Approach configuration should increase upward aerodynamic force.');
assert(approachLoads.force_wind_N(1) < cleanLoads.force_wind_N(1), ...
    'Approach configuration should increase drag magnitude.');
assert(norm(cleanLoads.wind_to_body_dcm' * cleanLoads.wind_to_body_dcm ...
    - eye(3)) < 1e-10, ...
    'Wind-to-body DCM must be orthonormal.');

shiftOptions = struct();
shiftOptions.aero = aero;
shiftOptions.aero_reference_point_body_m = [5.0; 0.0; 0.0];
shiftOptions.cg_body_m = [0.0; 0.0; 0.0];
shiftLoads = b777_aero_forces_moments(state, control, "clean", shiftOptions);
expectedShiftMoment = cross( ...
    shiftOptions.aero_reference_point_body_m ...
        - shiftOptions.cg_body_m, ...
    shiftLoads.force_body_N);
assertVectorClose(shiftLoads.cg_shift_moment_body_Nm, ...
    expectedShiftMoment, 1e-6, 'CG-shift aerodynamic moment');
assertVectorClose(shiftLoads.moment_body_Nm, ...
    shiftLoads.moment_reference_body_Nm + expectedShiftMoment, ...
    1e-6, 'CG-shift total aerodynamic moment');

bodyState = rmfield(state, {'V_mps', 'alpha_rad', 'beta_rad', ...
    'p_radps', 'q_radps', 'r_radps'});
bodyState.u = state.V_mps * cos(state.alpha_rad) * cos(state.beta_rad);
bodyState.v = state.V_mps * sin(state.beta_rad);
bodyState.w = state.V_mps * sin(state.alpha_rad) * cos(state.beta_rad);
bodyState.p = state.p_radps;
bodyState.q = state.q_radps;
bodyState.r = state.r_radps;
bodyLoads = b777_aero_forces_moments(bodyState, control, "clean");
assertClose(bodyLoads.coeff.CL, cleanLoads.coeff.CL, 1e-12, ...
    'body-velocity state adapter CL');
assertClose(bodyLoads.coeff.Cm, cleanLoads.coeff.Cm, 1e-12, ...
    'body-velocity state adapter Cm');

elevatorControl = control;
elevatorControl.delta_e_rad = deg2rad_local(1.0);
elevatorCoeff = aero.coeff(state, elevatorControl, "clean");
assert(elevatorCoeff.Cm < clean.Cm, ...
    'Positive elevator command should reduce pitching moment coefficient.');
assertClose(elevatorCoeff.CL - clean.CL, ...
    derivativeSeed.control.CL_delta_e * elevatorControl.delta_e_rad, ...
    1e-12, 'DATCOM-ready elevator lift residual');
assertClose(elevatorCoeff.CD - clean.CD, ...
    derivativeSeed.control.CD_delta_e * elevatorControl.delta_e_rad^2, ...
    1e-12, 'DATCOM-ready elevator drag residual');
assertClose(elevatorCoeff.Cm - clean.Cm, ...
    derivativeSeed.control.Cm_delta_e * elevatorControl.delta_e_rad, ...
    1e-12, 'DATCOM-ready elevator moment residual');

fprintf('Feature test passed: aerodynamic database is internally consistent.\n');

function tf = hasSource(sources, id)
tf = false;
for k = 1:numel(sources)
    tf = tf || sources(k).id == id;
end
end

function tf = hasDerivative(derivatives, id)
tf = false;
for k = 1:numel(derivatives)
    tf = tf || derivatives(k).id == id;
end
end

function assertRange(value, lowerBound, upperBound, label)
assert(value >= lowerBound && value <= upperBound, ...
    '%s is outside expected range: %.8g', label, value);
end

function assertClose(value, expected, tolerance, label)
assert(abs(value - expected) <= tolerance, ...
    '%s mismatch: got %.16g, expected %.16g', label, value, expected);
end

function assertVectorClose(value, expected, tolerance, label)
assert(all(abs(value(:) - expected(:)) <= tolerance), ...
    '%s mismatch: got [%g %g %g], expected [%g %g %g]', ...
    label, value(1), value(2), value(3), ...
    expected(1), expected(2), expected(3));
end

function data = readPartialDerivativeCsv(csvFile)
fid = fopen(char(csvFile), 'r');
assert(fid >= 0, 'Unable to open derivative candidate CSV: %s', csvFile);
cleanup = onCleanup(@() fclose(fid));
raw = textscan(fid, '%s%s%s%s%f%s%s%f%s', ...
    'Delimiter', ',', ...
    'HeaderLines', 1, ...
    'Whitespace', '', ...
    'CollectOutput', false);

sourceId = string(raw{1});
group = string(raw{2});
coefficient = string(raw{3});
value = raw{5};
status = string(raw{7});
confidence = raw{8};

finiteRows = isfinite(value) & isfinite(confidence);
sourceId = sourceId(finiteRows);
group = group(finiteRows);
coefficient = coefficient(finiteRows);
value = value(finiteRows);
status = status(finiteRows);

assert(~isempty(value), 'Derivative candidate CSV must not be empty.');
data = struct();
data.source_id = unique(sourceId, 'stable');
data.status = unique(status, 'stable');
assert(numel(data.source_id) == 1, ...
    'Derivative candidate CSV must use one source id.');
assert(numel(data.status) == 1, ...
    'Derivative candidate CSV must use one status.');

for k = 1:numel(value)
    groupName = char(group(k));
    coefficientName = char(coefficient(k));
    assert(isvarname(groupName) && isvarname(coefficientName), ...
        'Invalid derivative candidate name at row %d.', k + 1);
    data.(groupName).(coefficientName) = value(k);
end
end

function rad = deg2rad_local(deg)
rad = deg * pi / 180.0;
end
