%STARTUP Configure MATLAB paths for the B777-like NMPC project.

projectRoot = fileparts(mfilename('fullpath'));
projectFolders = { ...
    'data', ...
    'tests', ...
    'plant', ...
    'nmpc', ...
    'guidance', ...
    'validation' ...
};

for k = 1:numel(projectFolders)
    folderPath = fullfile(projectRoot, projectFolders{k});
    if isfolder(folderPath)
        addpath(genpath(folderPath));
    end
end

clear folderPath k projectFolders projectRoot;
